#image: registry.gitlab.com/mpapp-private/manuscripts-frontend/node8-aws

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  script:
    - npm ci
    - npm test
    - npm run coverage
  tags:
    - nodejs
  artifacts:
    paths:
      - coverage/
    expire_in: 1 week
    when: always

publish:
  stage: deploy
  only:
    refs:
      - master
  script:
    - npm ci
    - npx @manuscripts/publish
  tags:
    - nodejs
