#image: registry.gitlab.com/mpapp-private/manuscripts-frontend/node8-aws

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm run build
    - npm run coverage
  artifacts:
    paths:
      - ./coverage
    expire_in: 1 week
    when: always

test:
  stage: test
  script:
    - npm ci
    - npm test
  tags:
    - nodejs

publish:
  stage: deploy
  only:
    refs:
      - master
  script:
    - echo Running release
    - npm ci
    - npx @manuscripts/publish
  tags:
    - nodejs
